# -*- coding: utf-8 -*-
"""LANE 4 — build the GHL Book: ALL contacts, one row each, injected into the
dashboard as a static snapshot section (GHL is local-only; no live layer can
reach it). Rerunnable: replaces the section between the marker comments.
Data: ops/archive/ghl/<date>/raw/. Injects into ops/dashboard/apw_command_board.html.
"""
import json, sys, datetime, pathlib, re, html, urllib.parse
from collections import Counter

DATE = sys.argv[1] if len(sys.argv) > 1 else datetime.date.today().isoformat()
REPO = pathlib.Path(__file__).resolve().parent.parent.parent
RAW = REPO / "ops" / "archive" / "ghl" / DATE / "raw"
BOARD = REPO / "ops" / "dashboard" / "apw_command_board.html"
J = lambda n: json.load(open(RAW / f"{n}.json", encoding="utf-8"))

contacts = J("contacts")
details = J("contact_details")
appts = J("appointments_by_contact")
convs = J("conversations")
msgs = J("messages_by_conversation")
opps = J("opportunities")
pipes = {p["id"]: p for p in J("pipelines")["pipelines"]}

opp_by_contact = {}
for o in opps:
    opp_by_contact.setdefault(o.get("contactId"), []).append(o)

conv_by_contact = {}
for cvid, cv in convs.items():
    conv_by_contact.setdefault(cv.get("contactId"), []).append(cvid)

def ms(t):
    try: return datetime.datetime.fromisoformat(str(t).replace("Z", "+00:00")).timestamp() * 1000
    except Exception: return None

def stl_minutes(c):
    created = ms(c.get("dateAdded")); first = None
    for cvid in conv_by_contact.get(c["id"], []):
        for m in msgs.get(cvid, []):
            if (m.get("direction") or "").lower() != "outbound": continue
            t = ms(m.get("dateAdded"))
            if t and (first is None or t < first): first = t
    return round((first - created) / 60000) if (first and created and first >= created) else None

def campaign_of(c):
    d = details.get(c["id"], {})
    for src in (d.get("attributionSource") or {}, d.get("lastAttributionSource") or {}):
        url = src.get("url")
        if url and "?" in url:
            q = urllib.parse.parse_qs(url.split("?", 1)[1])
            if q.get("utm_campaign"): return q["utm_campaign"][0]
        if src.get("campaign"): return src["campaign"]
    return ""

SHORT = {"SCIO | Application | Professionals/Biz Owners | Images - relaunch": "W2/BizOwner relaunch",
         "SCIO | Application | Medical | New Videos Relaunch - v2": "Medical relaunch v2"}

rows = []
for c in contacts:
    cid = c["id"]
    nm = f'{c.get("firstNameRaw") or c.get("firstName") or ""} {c.get("lastNameRaw") or c.get("lastName") or ""}'.strip() or "(no name)"
    ap = appts.get(cid, [])
    ap_txt = " · ".join(f'{(e.get("appointmentStatus") or "?")} {str(e.get("startTime"))[:10]}' for e in ap)
    oo = opp_by_contact.get(cid, [])
    opp_txt = ""
    if oo:
        o = oo[0]
        p = pipes.get(o.get("pipelineId"), {})
        stage = next((s["name"] for s in p.get("stages", []) if s["id"] == o.get("pipelineStageId")), "?")
        stage = re.sub(r"[^\w /&-]", "", stage).strip()
        opp_txt = f'{stage} ({o.get("status")})' + (f' ${o.get("monetaryValue"):,.0f}'.replace(".0", "") if o.get("monetaryValue") else "")
    camp = campaign_of(c)
    camp = SHORT.get(camp, camp)
    nmsg = sum(len(msgs.get(v, [])) for v in conv_by_contact.get(cid, []))
    # presence flags only — raw email/phone stay in the local CSVs and the linked
    # GHL record, never embedded in the hosted page
    rows.append([nm, cid, str(c.get("dateAdded"))[:10], c.get("source") or "", camp,
                 "yes" if c.get("email") else "", "yes" if c.get("phone") else "", len(ap), ap_txt, opp_txt,
                 stl_minutes(c), nmsg, "|".join(c.get("tags") or [])])
rows.sort(key=lambda r: r[2], reverse=True)

data_js = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
n = len(rows)
n_appt = sum(1 for r in rows if r[7])
n_camp = sum(1 for r in rows if r[4])
n_stl = sum(1 for r in rows if r[10] is not None)

section = f"""<!-- GHLBOOK:START (generated by ops/lane4/build_ghl_book.py — do not hand-edit) -->
<section id="ghlbook">
  <div class="sec-head"><span class="mark">03d</span><h2>GHL Book — every contact in the system ({n})</h2>
    <span class="note">snapshot {DATE} · GHL is local-only, so this table refreshes with each local pull, not live</span></div>
  <div class="panel">
    <p class="sub">The whole GHL location, no filter: {n} contacts — {n_appt} ever booked, {n_camp} carry ad attribution, {n_stl} have a measurable first-touch. The 104-row tracker above is the worked subset; this is everyone. <strong style="color:var(--ink)">Name → the GHL contact record</strong> (needs GHL login). Speed-to-lead = contact created → first outbound message/call, from raw GHL messages. 📞/✉️ mark phone/email on file — the values live in the GHL record (click the name) and the local pull CSVs, kept off this hosted page deliberately.</p>
    <div style="display:flex; gap:10px; flex-wrap:wrap; margin:10px 0 14px">
      <input id="ghl-search" type="search" placeholder="Search name / tag / source…" style="background:var(--raised); border:1px solid var(--line); color:var(--ink); border-radius:6px; padding:7px 12px; font-size:13px; font-family:inherit; min-width:240px">
      <select id="ghl-filter" style="background:var(--raised); border:1px solid var(--line); color:var(--ink); border-radius:6px; padding:7px 10px; font-size:13px; font-family:inherit">
        <option value="">Everyone</option><option value="appt">Booked at least once</option><option value="noappt">Never booked</option><option value="camp">Ad-attributed</option><option value="showed">Marked showed</option><option value="noshow">Marked no-show</option><option value="cancelled">Cancelled</option>
      </select>
      <span class="sub" style="align-self:center; margin:0"><span id="ghl-shown">{n}</span> shown</span>
    </div>
    <div class="tbl-wrap"><table style="min-width:1080px">
      <thead><tr><th>Person</th><th>Created</th><th>Source</th><th>Campaign</th><th>Contact</th><th class="num">Appts</th><th>Appt history (status · date)</th><th>Opportunity</th><th class="num">StL min</th><th class="num">Msgs</th><th>Tags</th></tr></thead>
      <tbody id="ghl-body"></tbody>
    </table></div>
  </div>
</section>
<script>
  (function () {{
    var DATA = {data_js};
    var GHL = 'https://app.gohighlevel.com/v2/location/WFkoNzKa9J9PxhngsLfl/contacts/detail/';
    var body = document.getElementById('ghl-body'), shown = document.getElementById('ghl-shown');
    var q = document.getElementById('ghl-search'), f = document.getElementById('ghl-filter');
    function esc(s) {{ var d = document.createElement('div'); d.textContent = s == null ? '' : String(s); return d.innerHTML; }}
    function render() {{
      var needle = (q.value || '').toLowerCase(), mode = f.value, out = [], count = 0;
      DATA.forEach(function (r) {{
        var hay = (r[0] + ' ' + r[3] + ' ' + r[4] + ' ' + r[12]).toLowerCase();
        if (needle && hay.indexOf(needle) === -1) return;
        if (mode === 'appt' && !r[7]) return;
        if (mode === 'noappt' && r[7]) return;
        if (mode === 'camp' && !r[4]) return;
        if ((mode === 'showed' || mode === 'noshow' || mode === 'cancelled') && r[8].indexOf(mode) === -1) return;
        count++;
        var contact = ((r[6] ? '📞 ' : '') + (r[5] ? '✉️' : '')) || '—';
        out.push('<tr><td class="who"><a href="' + GHL + esc(r[1]) + '">' + esc(r[0]) + '</a></td>' +
          '<td class="mono">' + esc(r[2]) + '</td><td class="why">' + esc(r[3]) + '</td>' +
          '<td class="why">' + esc(r[4]) + '</td><td>' + contact + '</td>' +
          '<td class="num mono">' + (r[7] || '') + '</td><td class="why">' + esc(r[8]) + '</td>' +
          '<td class="why">' + esc(r[9]) + '</td><td class="num mono">' + (r[10] == null ? '' : esc(r[10])) + '</td>' +
          '<td class="num mono">' + (r[11] || '') + '</td><td class="why" style="max-width:32ch">' + esc(r[12]) + '</td></tr>');
      }});
      body.innerHTML = out.join('');
      shown.textContent = count;
    }}
    q.addEventListener('input', render); f.addEventListener('change', render);
    render();
  }})();
</script>
<!-- GHLBOOK:END -->
"""

htmltext = BOARD.read_text(encoding="utf-8")
htmltext = re.sub(r"<!-- GHLBOOK:START.*?<!-- GHLBOOK:END -->\n?", "", htmltext, flags=re.S)
V57_ANCHOR = "</div><!-- /prospects -->"   # v5.7+ tabbed board: append inside the Prospects pane
LEGACY_ANCHOR = "<!-- ============ REVENUE LEDGER ============ -->"
if V57_ANCHOR in htmltext:
    htmltext = htmltext.replace(V57_ANCHOR, section + "\n" + V57_ANCHOR)
else:
    if 'href="#ghlbook"' not in htmltext:
        htmltext = htmltext.replace('<a href="#people">Every Person</a>',
                                    '<a href="#people">Every Person</a>\n  <a href="#ghlbook">GHL Book</a>')
    htmltext = htmltext.replace(LEGACY_ANCHOR, section + "\n" + LEGACY_ANCHOR)
BOARD.write_text(htmltext, encoding="utf-8")
print(f"injected GHL Book: {n} contacts ({n_appt} booked, {n_camp} attributed, {n_stl} w/ StL) -> {BOARD}")
