# -*- coding: utf-8 -*-
"""LANE 4 — CANON_NUMBERS.json: the single source of truth every lane bakes
into its snapshot (dashboard SNAP, register, reports). Regenerated by every
local GHL pull. No PII — counts, dispositions, and IDs only.
"""
import json, sys, datetime, pathlib
from collections import Counter

DATE = sys.argv[1] if len(sys.argv) > 1 else datetime.date.today().isoformat()
REPO = pathlib.Path(__file__).resolve().parent.parent.parent
RAW = REPO / "ops" / "archive" / "ghl" / DATE / "raw"
OUT = REPO / "ops" / "data" / "CANON_NUMBERS.json"
J = lambda n: json.load(open(RAW / f"{n}.json", encoding="utf-8"))

contacts = J("contacts")
appts = J("appointments_by_contact")
convs = J("conversations")
msgs = J("messages_by_conversation")
opps = J("opportunities")
details = J("contact_details")

appt_status = Counter((e.get("appointmentStatus") or "?").lower() for evs in appts.values() for e in evs)
opp_status = Counter(o.get("status") for o in opps)
msg_types = Counter((m.get("messageType") or "?").replace("TYPE_", "") for mm in msgs.values() for m in mm)

def has_attr(cid):
    d = details.get(cid, {})
    return bool(d.get("attributionSource") or d.get("lastAttributionSource"))

canon = {
    "_meta": {
        "source": "GHL location WFkoNzKa9J9PxhngsLfl, local pull (LANE 4)",
        "pull_date": DATE,
        "law": "These figures are VERIFIED from raw GHL API responses (ops/archive/ghl/%s/raw/). Lanes bake these into snapshots verbatim; do not hand-edit this file." % DATE,
    },
    "contacts": {
        "total": len(contacts),
        "with_email": sum(1 for c in contacts if c.get("email")),
        "with_phone": sum(1 for c in contacts if c.get("phone")),
        "with_attribution": sum(1 for c in contacts if has_attr(c["id"])),
        "dnd": sum(1 for c in contacts if c.get("dnd")),
    },
    "appointments": {
        "events": sum(len(v) for v in appts.values()),
        "unique_bookers": len(appts),
        "statuses": dict(appt_status),
        "status_note": "confirmed = never updated after the call (not a show); see register #64",
    },
    "dispositions_vs_roster_audit": {
        "audit_unknown_events": 79,
        "resolved_by_ghl": 16,
        "resolved_breakdown": {"cancelled": 10, "noshow": 6},
        "unresolvable_from_ghl": 63,
        "evidence": "ops/archive/ghl/%s/ROSTER_RECONCILIATION.md" % DATE,
    },
    "opportunities": {"total": len(opps), "by_status": dict(opp_status)},
    "conversations": {"total": len(convs), "messages": sum(len(v) for v in msgs.values()),
                      "by_channel": dict(msg_types)},
    "payments": {"orders": 0, "transactions": 0, "subscriptions": 0, "invoices": 0,
                 "note": "GHL Payments EMPTY — money moves via Whop (register #65b); Nick $500 / Jill installments unverifiable in GHL"},
    "tracker_cross_ref": {
        "notion_tracked_leads": 104,
        "ghl_only_contacts": len(contacts) - 104,
        "note": "104 = Clients & Leads rows after the 8/30 recovery of 21 ad-leads (register #69)",
    },
}
OUT.write_text(json.dumps(canon, indent=1), encoding="utf-8")
print(json.dumps(canon["contacts"], indent=None), "| appts:", dict(appt_status))
print("->", OUT)
